### ISSUE TITLE
2018~2019冬 广二避寒记 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#15]
https://www.ouuan.cf/2018-2019%E5%86%AC-%E5%B9%BF%E4%BA%8C%E9%81%BF%E5%AF%92%E8%AE%B0/ 

 突然就得知了要去广二集训。 然后知道了这次出去可能要一直到 WC，差不多有 $50$ 天。这样一算这个学期我在武汉的时间可能和外出的时间一样多了。 毕竟是去广州，会暖和很多，也许看不到武汉的雪了。 Day 0Railway在站台上遇到了 Dew、ylh，感觉自己活尸化严重，都是我妈先看见的… 中午吃了泡面（有汤的那种），之前出去都比较近，在火车上不用吃饭，印象中上次吃方便面还是初三的时候在学校里吃

**Comment by wjy-yy** [comment]
%%%ouuan orz

**Comment by EternalAlexander** [comment]
%%%ouuan orz

**Comment by ButterflyDew** [comment]
%%%ouuan orz

**Comment by huyufeifei** [comment]
%%%ouuan orz

**Comment by wjy-yy** [comment]
>polygon真有意思！试着把一道题搞上去了。

您已经开始筹备CF了%%%

**Comment by hydingsy** [comment]
%%%ouuan orz

**Comment by XTZORZ** [comment]
偶然点进来膜膜您QwQ

**Comment by XTZORZ** [comment]
外省蒟蒻偶然点进来，膜膜ouuan神犇QwQ

**Comment by ywwywwyww** [comment]
%%%ouuan orz

**Comment by ouuan** [comment]
> @ywwywwyww
> %%%ouuan orz

天天被您dd/kk

**Comment by dreamfarwhb** [comment]
你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你

**Comment by ouuan** [comment]
> @dreamfarwhb
> 你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你
> 

不是很懂“夏令营甚至参加比赛”，这两个有什么不同吗..

CCF 的 WC 一般是要求 NOIP 分数，根据不同省份分数线不同，一般是比 NOIP 一等奖高的。THU 和 PKU 的 WC/SC 要填申请表，WC 主要还是看 NOIP 成绩，SC 可能还会看省选成绩之类的，所在年级和文化课成绩可能也会有一定影响。时间的话 T/PWC 一般是 CCF WC 前后（1 月底左右），T/PSC 一般是 CTS、APIO 前后（5 月左右）

**Comment by dreamfarwhb** [comment]
> @ouuan
> > @dreamfarwhb
> > 你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你
> > 
> 
> 不是很懂“夏令营甚至参加比赛”，这两个有什么不同吗..
> 
> CCF 的 WC 一般是要求 NOIP 分数，根据不同省份分数线不同，一般是比 NOIP 一等奖高的。THU 和 PKU 的 WC/SC 要填申请表，WC 主要还是看 NOIP 成绩，SC 可能还会看省选成绩之类的，所在年级和文化课成绩可能也会有一定影响。时间的话 T/PWC 一般是 CCF WC 前后（1 月底左右），T/PSC 一般是 CTS、APIO 前后（5 月左右）

多谢解答，我不是很懂，没有描述清楚，夏令营也是比赛，我想问一下，比赛的顺序是不是noip->noi->ccf wc->cts->apio吧？  谢谢

**Comment by dreamfarwhb** [comment]
> @ouuan
> > @dreamfarwhb
> > 你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你
> > 
> 
> 不是很懂“夏令营甚至参加比赛”，这两个有什么不同吗..
> 
> CCF 的 WC 一般是要求 NOIP 分数，根据不同省份分数线不同，一般是比 NOIP 一等奖高的。THU 和 PKU 的 WC/SC 要填申请表，WC 主要还是看 NOIP 成绩，SC 可能还会看省选成绩之类的，所在年级和文化课成绩可能也会有一定影响。时间的话 T/PWC 一般是 CCF WC 前后（1 月底左右），T/PSC 一般是 CTS、APIO 前后（5 月左右）

多谢解答，我不是很懂，没有描述清楚，夏令营也是比赛，我想问一下，比赛的顺序是不是noip->noi->ccf wc->cts->apio吧？  谢谢

**Comment by ouuan** [comment]
> @dreamfarwhb
> > @ouuan
> > > @dreamfarwhb
> > > 你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你
> > > 
> > 
> > 不是很懂“夏令营甚至参加比赛”，这两个有什么不同吗..
> > 
> > CCF 的 WC 一般是要求 NOIP 分数，根据不同省份分数线不同，一般是比 NOIP 一等奖高的。THU 和 PKU 的 WC/SC 要填申请表，WC 主要还是看 NOIP 成绩，SC 可能还会看省选成绩之类的，所在年级和文化课成绩可能也会有一定影响。时间的话 T/PWC 一般是 CCF WC 前后（1 月底左右），T/PSC 一般是 CTS、APIO 前后（5 月左右）
> 
> 多谢解答，我不是很懂，没有描述清楚，夏令营也是比赛，我想问一下，比赛的顺序是不是noip->noi->ccf wc->cts->apio吧？  谢谢
>  

时间上 NOIP 11 月，WC 1 月，CTS / APIO 5 月，NOI 7 月。

国家队选拔流程上，NOIP（达到省选分数线）→ 省队选拔（进入省队）→ NOI（进入国家集训队）→ WC（进入国家候选队）→ CTS（进入国家队）。有的比赛还可以作为非正式选手参加，不计入选拔。

**Comment by dreamfarwhb** [comment]
> @ouuan
> > @dreamfarwhb
> > > @ouuan
> > > > @dreamfarwhb
> > > > 你好，我想后面参加夏令营甚至参加比赛，要具备什么条件，比如考试成绩、时间以及其他可能的要求？我想先提前准备着，谢谢你
> > > > 
> > > 
> > > 不是很懂“夏令营甚至参加比赛”，这两个有什么不同吗..
> > > 
> > > CCF 的 WC 一般是要求 NOIP 分数，根据不同省份分数线不同，一般是比 NOIP 一等奖高的。THU 和 PKU 的 WC/SC 要填申请表，WC 主要还是看 NOIP 成绩，SC 可能还会看省选成绩之类的，所在年级和文化课成绩可能也会有一定影响。时间的话 T/PWC 一般是 CCF WC 前后（1 月底左右），T/PSC 一般是 CTS、APIO 前后（5 月左右）
> > 
> > 多谢解答，我不是很懂，没有描述清楚，夏令营也是比赛，我想问一下，比赛的顺序是不是noip->noi->ccf wc->cts->apio吧？  谢谢
> >  
> 
> 时间上 NOIP 11 月，WC 1 月，CTS / APIO 5 月，NOI 7 月。
> 
> 国家队选拔流程上，NOIP（达到省选分数线）→ 省队选拔（进入省队）→ NOI（进入国家集训队）→ WC（进入国家候选队）→ CTS（进入国家队）。有的比赛还可以作为非正式选手参加，不计入选拔。APIO 不在体系内。

多谢，非常清晰的回答。
