### ISSUE TITLE
随机图片征稿

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#19]
长期接收随机图片投稿，将图片链接发至此 issue 即可。

要求图片为横屏图片。

[随机图片-人物类](https://www.ouuan.cf/randpic/people/)

[随机图片-风景类](https://www.ouuan.cf/randpic/scenery/)

**Comment by ouuan** [comment]
果然没人QAQ

**Comment by code004Accepted** [comment]
其实已经有这样的api了qwq 

BingEverydayWallpaperPicture: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture

~~可以直接写个脚本把每次获取到的图片下载下来~~，这个网址的优点就是它不会像多数api那样简单地随机跳转到一个壁纸，而是在原页面显示不同壁纸，这样就可以做到不断刷新获取不同图片

前排膜拜%%%

**Comment by code004Accepted** [comment]
Why close it? qwq...

**Comment by ouuan** [comment]
emm...把 gitalk 那些 close 了，就顺手把这个 close 了。

（只不过现在也的确不打算征稿了）

**Comment by code004Accepted** [comment]
刚刚看到了，打算也处理一下qwq Gitalk看起来确实比较危险...

**Comment by ouuan** [comment]
大致看了一下，感觉好像是只要使用 App 的人不干坏事就没什么问题。其他人如果知道了你的 client_id 和 client_secret 好像不会直接造成影响，但他可以拿你的 App 去干坏事。（大致了解了一下，不一定准确。）

**Comment by ouuan** [comment]
这样的话，主要就是让访客更加放心吧。

**Comment by code004Accepted** [comment]
嗯，我已经revoke所有gitalk的access了qwq 当时完全没仔细看
看您在 #84 里提到的文章，看起来还是挺危险的 而且我也不怎么喜欢Gitalk的风格（那种Preview还要单独点按钮然后卡半天的）
还有，在Gitalk中如果你输完评论先点Preview再Comment，Comment成功后Preview并不会自动清空（似乎是个Bug
