### ISSUE TITLE
关于 | ouuan's blog

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#2]
http://www.ouuan.cf/about/ 

 简介ouuan，HB高一oier。 洛谷 CF 博客园 b站 友链Dew wjyyy Sooke huyufeifei Rye_Catcher 额冻豆腐 QAQ初三： NOIP2017普及组一等 $230$ NOIP2017提高组二等 $160$（HB $rank43$） HBSX2018非正式选手 $180$（HB $rank4$） 高一： NOIP2018提高组一等 $489$（CN $ran

**Comment by ouuan** [comment]
“现役 oier” 这个词给人的感觉都随着时间而不同了（

**Comment by qwqbear** [comment]
百度ouuan ,多一个空格就可以了

**Comment by qwqbear** [comment]
用coding好像更快点

**Comment by qwqbear** [comment]
orzzzzzz
