### ISSUE TITLE
html实现随机图片 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#20]
https://www.ouuan.cf/html%E5%AE%9E%E7%8E%B0%E9%9A%8F%E6%9C%BA%E5%9B%BE%E7%89%87/ 

 注：暂时还不知道如何制作能被引用的随机图片，只能查看图片，而不能通过类似于![](图片地址)的方式查看。   demo 欢迎投稿图片：投稿地址  核心代码12345&lt;script type="text/javascript" src="imagelist.json"&gt;&lt;/script&gt;&lt;script type="text/javascript"&gt;  var r

**Comment by Alpha1022** [comment]
要做那种的话得 PHP  
您需要设置 Response Header 的 `Content-Type` 为 `image/jpeg` 或 `image/png` 然后 `file_get_contents()` 之类的

**Comment by Alpha1022** [comment]
好像纯 HTML 是可以的……  
可以用 meta http-equiv 指定 Response Header 然后 `JavaScript document.write()`
