### ISSUE TITLE
浅谈邻项交换排序的应用以及需要注意的问题 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#21]
https://www.ouuan.cf/%E6%B5%85%E8%B0%88%E9%82%BB%E9%A1%B9%E4%BA%A4%E6%8D%A2%E6%8E%92%E5%BA%8F%E7%9A%84%E5%BA%94%E7%94%A8%E4%BB%A5%E5%8F%8A%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by ouuan** [comment]
一个补充说明：如果觉得“不具有不可比性的传递性”不好理解的话，有个简单的例子：P(x,y)=x+1<y。这个偏序关系满足非自反性（x+1≮x）、非对称性和传递性（x+2<y+1<z），但不满足不可比性的传递性（1+1=2，2+1=3，1+1<3）。

**Comment by woshiluo** [comment]
QAQ 谢谢大佬，讲的超清楚的
