### ISSUE TITLE
UER #8 游记 —— 通信题：打雪仗 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#27]
https://ouuan.github.io/UER-8-%E6%B8%B8%E8%AE%B0-%E2%80%94%E2%80%94-%E9%80%9A%E4%BF%A1%E9%A2%98%EF%BC%9A%E6%89%93%E9%9B%AA%E4%BB%97/ 

 为什么这篇博客又是游记又是题解呢？因为这是我做的第一道通信题！感觉通信题真有意思QAQ. T3随便打了打暴力，T2由于没啥时间了感觉rush不出来就没写。（没错这就是这篇“游记”里唯一和通信题无关的部分） T1题目链接 大意：Alice 有一个长度为 $2n$ 的 $01$ 串 $s_{1..2n}$，Bob 有 $n$ 个下标 $p_{1..n}$，Alice 和 Bob 只能用 $01$ 通信

**Comment by ButterflyDew** [comment]
感觉蛮有意思的
