### ISSUE TITLE
ouuanの漫评 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#28]
https://ouuan.github.io/ouuan%E3%81%AE%E6%BC%AB%E8%AF%84/ 

 从看的第一部番——LL起，我在看完一部番后，如果有什么感想，就会当天在qq空间发一段说说。我虽然看番少，但一般都会看一些令人思考、有所收获的番，几年下来也写了有一些了。偶尔自己翻看也不太方便，现在也有了这个博客，就整理在这好了。其实也不是完全的漫评，看完一部番，有什么想说的，写下来，大约就是如此。

**Comment by zeronsama** [comment]
%%%dalao

# μ'sic forever!!!!
