### ISSUE TITLE
n方过百万 暴力碾标算——指令集优化的基础使用 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#30]
https://ouuan.github.io/n%E6%96%B9%E8%BF%87%E7%99%BE%E4%B8%87-%E6%9A%B4%E5%8A%9B%E7%A2%BE%E6%A0%87%E7%AE%97%E2%80%94%E2%80%94%E6%8C%87%E4%BB%A4%E9%9B%86%E4%BC%98%E5%8C%96%E7%9A%84%E5%9F%BA%E7%A1%80%E4%BD%BF%E7%94%A8/ 

 感谢 yfz 和 mcfx 在 WC 营员交流上的分享！ 然而只看那个课件来学习指令集好像略有困难..所以我来分享一下我自学一晚上的成果。 希望能帮助大家暴力过题，考场上再也写不出标算。 你问学了指令集之后如何保持对标算的信仰？当然是每天%神橡树 ok不扯了，进入正题…

**Comment by yfzcsc** [comment]
读入数据时鬼才用`_mm256_set_epi32`，直接`scanf("%d",((int*)A)+i);`就行了

**Comment by ouuan** [comment]
> @yfzcsc
> 读入数据时鬼才用`_mm256_set_epi32`，直接`scanf("%d",((int*)A)+i);`就行了

我菜了..

**Comment by yyhqwq** [comment]
终于找到了个讲卡常比较靠谱的 资瓷！ Orz

**Comment by bluecloudi** [comment]
Orz %%% ouuan dalao
