### ISSUE TITLE
后缀数组学习笔记 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#36]
https://ouuan.github.io/%E5%90%8E%E7%BC%80%E6%95%B0%E7%BB%84%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/ 

 后缀数组是一种处理字符串问题的有力工具（废话），本文的主要特点是一步步地由最朴素的后缀数组构建方法逐步优化，而非直接给出最终优化后的代码。 希望这篇文章能让更多的人看懂后缀数组的代码，学会后缀数组。

**Comment by yclrz** [comment]
赞啊！

**Comment by wjy-yy** [comment]
为什么不讲怎么基数排序啊qaq

我基数排序写的常数极大几乎$\sout{O(n\log n)}$

**Comment by wjy-yy** [comment]
以前以为基数排序跟计数排序是一个东西

怪不得我学不会SA ![哭](http://www.wjyyy.top/wp-content/uploads/2018/10/IMG_4129.png)
