### ISSUE TITLE
cdq分治学习笔记 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#50]
https://ouuan.github.io/cdq%E5%88%86%E6%B2%BB%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/ 

 cdq分治也是咕了好久了..最近总算把它学了。 cdq分治是一种离线算法，可以代替一些复杂的数据结构，降低代码难度，减小常数。废话大家都知道。

**Comment by GitPinkRabbit** [comment]
![](https://loj-img.upyun.menci.memset0.cn/2019/04/02/5ca378640d2ff.jpg)
