### ISSUE TITLE
十二省联考2019 游记 & 题解 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#53]
https://ouuan.github.io/%E5%8D%81%E4%BA%8C%E7%9C%81%E8%81%94%E8%80%832019-%E6%B8%B8%E8%AE%B0-%E9%A2%98%E8%A7%A3/ 

 口中喊着「僕勝つから。ぜったい、勝て来るから。」的你，真的付出了桐山般的努力吗？

**Comment by GitPinkRabbit** [comment]
膜 ouuan！
