### ISSUE TITLE
使用 testlib.h 写 lemon SPJ | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#63]
https://ouuan.github.io/%E4%BD%BF%E7%94%A8-testlib-h-%E5%86%99-lemon-SPJ/ 

 不用 testlib.h 是不可能写好 checker 的（逃

**Comment by EntropyIncreaser** [comment]
其实呢……毛爷爷魔改出来过一个对接 Lemon 的 testlib：https://pastebin.com/JdYUu6m0
