### ISSUE TITLE
Codeforces Round #564 中文题解 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#64]
https://ouuan.github.io/Codeforces-Round-564-%E4%B8%AD%E6%96%87%E9%A2%98%E8%A7%A3/ 

 准备了半年的 cf 就这样结束了…赛前四天连撞两题过于刺激，所以比赛也有很多没有准备充分的地方。 想看赛前四天紧急换题精心准备半年 cf 的经历吗？就在本博客，台前幕后正在咕咕中。

**Comment by foreverlasting1202** [comment]
前排orz

**Comment by Lxy-Tql** [comment]
捕捉rk1巨佬！

**Comment by StudyingFather** [comment]
前排Orz

**Comment by memset0** [comment]
前排 orz

**Comment by hydingsy** [comment]
前排 orz

**Comment by libra9z** [comment]
### 前排 orz

**Comment by shiguotao1139** [comment]
强啊

**Comment by shiguotao1139** [comment]
1E谁能在两小时里写出，绝对神仙

**Comment by jkloverdcoi** [comment]
orz

**Comment by zhangtingchuan** [comment]
前排Orz

**Comment by nealchen2003** [comment]
前排orz，顺便反馈1B的标签有后缀数据结构什么的混进来了。

**Comment by LMOliver** [comment]
后排 Orz

**Comment by shiguotao1139** [comment]
后排被AK

**Comment by iamqzh** [comment]
求问您1E的lct的Link操作为什么没有翻转qwq

**Comment by ouuan** [comment]
> @iamqzh
> 求问您1E的lct的Link操作为什么没有翻转qwq

因为树的形态固定，不需要换根。
