### ISSUE TITLE
bad round 与出题人的坚守 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#65]
https://ouuan.github.io/bad-round-%E4%B8%8E%E5%87%BA%E9%A2%98%E4%BA%BA%E7%9A%84%E5%9D%9A%E5%AE%88/ 

 等你等了五千年，只为这一刹那的回眸一笑。  这句话作为台前幕后的标准开头应该是没问题的。 只不过果然还是写不出 vfk 的水平啊…写的比较散乱。而且是前后断断续续地写的，有的写于赛前，有的写于赛后，所以会有行文不连贯的地方，可能也会有后来忘记修正的地方。

**Comment by StudyingFather** [comment]
前排资瓷！

**Comment by Xraywin** [comment]
第二排资瓷！

**Comment by wjy-yy** [comment]
命题组辛苦了！

**Comment by yltx** [comment]
此乃真出题人……我貌似连毒瘤大模拟和无意义DP都够不上……

**Comment by EntropyIncreaser** [comment]
一点也不 bad QwQ

**Comment by foreverlasting1202** [comment]
命题组辛苦了！

**Comment by zhangqingqi** [comment]
看得出这场比赛是精心准备的，每道题都很有水平！

**Comment by Planet6174** [comment]
命题组辛苦了

**Comment by GitPinkRabbit** [comment]
我自闭了，ouuan 就提到了一次我

**Comment by libra9z** [comment]
命题组辛苦了

**Comment by liubei121212** [comment]
> 我讨厌不用心的出题人，讨厌不严谨甚至误导人的博客，因为，我认为出题给别人做、写博客给别人看是应当对别人负责的。如果没有精力、不想负责的话，出题给自己做，博客保存在本地就好了，发出来干什么？即使是能力不够，也得有认真负责的态度才行。如果没有，别人骂你，只当骂醒好了。如果骂不醒，那着实该骂。


说的好啊！
