### ISSUE TITLE
ouuan 的出题规范 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#68]
https://ouuan.github.io/ouuan-%E7%9A%84%E5%87%BA%E9%A2%98%E8%A7%84%E8%8C%83/ 

 首先，你需要意识到，自己出的题是要给别人做的。

**Comment by QAQAutoMaton** [comment]
pretest这点我反对
另外“由于未使用搜索引擎查找导致自己不清楚有原题，从而出了“几乎一致”的原题。”感觉我被D了

**Comment by ouuan** [comment]
> @QAQAutoMaton
> pretest这点我反对
> 另外“由于未使用搜索引擎查找导致自己不清楚有原题，从而出了“几乎一致”的原题。”感觉我被D了

您反对尽量强还是尽量少啊...................................

能轻松搜到的那题并不太类似，真正非常类似的那题是 cy 提供的啊..

**Comment by Flower233pks** [comment]
ouuan好神神啊qwq

**Comment by QAQAutoMaton** [comment]
> @ouuan
> > @QAQAutoMaton
> > pretest这点我反对
> > 另外“由于未使用搜索引擎查找导致自己不清楚有原题，从而出了“几乎一致”的原题。”感觉我被D了
> 
> 您反对尽量强还是尽量少啊...................................
> 
> 能轻松搜到的那题并不太类似，真正非常类似的那题是 cy 提供的啊..

当然是反对尽量强

**Comment by ouuan** [comment]
> @QAQAutoMaton
> > @ouuan
> > > @QAQAutoMaton
> > > pretest这点我反对
> > > 另外“由于未使用搜索引擎查找导致自己不清楚有原题，从而出了“几乎一致”的原题。”感觉我被D了
> > 
> > 您反对尽量强还是尽量少啊...................................
> > 
> > 能轻松搜到的那题并不太类似，真正非常类似的那题是 cy 提供的啊..
> 
> 当然是反对尽量强
> 

您的题在 Sooke “尽量强”地出数据的情况下在 div.2 获得了 18.5% fst 率的好成绩啊...

**Comment by ForkFG** [comment]
顶顶！（蒟蒻最近在出题，感觉很有用）
@ouuan

**Comment by oierwanhong** [comment]
写的是真心好,受益匪浅

**Comment by william-song-shy** [comment]
@ouuan
数据的多样性与强度这章感觉有用
（不过您要能将自动生成数据如CYaRon的数据强度控制讲一下就更好了）

**Comment by ouuan** [comment]
> @william-song-shy
>  @ouuan
> 数据的多样性与强度这章感觉有用
> （不过您要能将自动生成数据如CYaRon的数据强度控制讲一下就更好了）
> 

CYaRon 的批量生成数据不如命令行参数 + bat 方便，其它方面的优点我觉得只有图和树的生成，但如果直接用它那个生成器强度是无法保证的吧。

**Comment by william-song-shy** [comment]
> > @william-song-shy
> > @ouuan
> > 数据的多样性与强度这章感觉有用
> > （不过您要能将自动生成数据如CYaRon的数据强度控制讲一下就更好了）
> 
> CYaRon 的批量生成数据不如命令行参数 + bat 方便，其它方面的优点我觉得只有图和树的生成，但如果直接用它那个生成器强度是无法保证的吧。

所以我想生成图或树且数据强度控制能很好保证的话要怎么办更好呢？

**Comment by ouuan** [comment]
> @william-song-shy
> > > @william-song-shy
> > > @ouuan
> > > 数据的多样性与强度这章感觉有用
> > > （不过您要能将自动生成数据如CYaRon的数据强度控制讲一下就更好了）
> > 
> > CYaRon 的批量生成数据不如命令行参数 + bat 方便，其它方面的优点我觉得只有图和树的生成，但如果直接用它那个生成器强度是无法保证的吧。
> 
> 所以我想生成图或树且数据强度控制能很好保证的话要怎么办更好呢？

自己造，具体题目具体分析..
