### ISSUE TITLE
Surreal Numbers 阅读笔记 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#72]
https://ouuan.github.io/Surreal-Numbers-%E9%98%85%E8%AF%BB%E7%AC%94%E8%AE%B0/ 

 今天模拟赛遇到了一道需要超现实数的题目，赛后在阅读 Matrix67 的博客 时听说了唐纳德所著的《Surreal Numbers》（中译：研究之美）这本书，于是就阅读了一下。 大约会把书里的定理证一遍吧.. 学习超现实数的时候请假装自己不知道关于数字的一切知识，并且不要把定义的名字真的当回事（某些定义有着熟悉的名字，但可能与我们熟知的意义相同，也可能不同）。 小说下载地址

**Comment by foreverlasting1202** [comment]
前排占坑

**Comment by alonenight** [comment]
gugugu?
