### ISSUE TITLE
NIO9102 落雨大 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#74]
https://ouuan.github.io/NIO9102-%E8%90%BD%E9%9B%A8%E5%A4%A7/ 

 我也来到 NOI 了，呢。

**Comment by nantf** [comment]
557219762和116195171是哪些天啊QwQ

**Comment by ouuan** [comment]
> 557219762和116195171是哪些天啊QwQ

（等比数列）

**Comment by ouuan** [comment]
> @nantf
> 557219762和116195171是哪些天啊QwQ

（等比数列）

**Comment by wknclizu** [comment]
orz

**Comment by huyufeifei** [comment]
坐G1152的说一下，我那辆车的插座不在前面座位的底下，在自己座垫和旁边坐垫之间靠下一点的位置。感觉放在这里会方便一点...
