### ISSUE TITLE
一些有趣的小工程 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#76]
https://ouuan.github.io/%E4%B8%80%E4%BA%9B%E6%9C%89%E8%B6%A3%E7%9A%84%E5%B0%8F%E5%B7%A5%E7%A8%8B/ 

 说实话我觉得竞赛题目挺坑爹的……木有啥意思。人类为何要出题刁难人类。 我更喜欢做的事情是写点工程啥的 &gt;_&lt;… 做做小游戏挺好玩的。 —— vfk 《四色的 NOI》  （这算哪门子引用啊）

**Comment by EternalAlexander** [comment]
orz

**Comment by code004Accepted** [comment]
%%% dalao
