### ISSUE TITLE
莫队、带修莫队、树上莫队详解 | ouuan的博客

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#8]
http://www.ouuan.cf/%E8%8E%AB%E9%98%9F%E3%80%81%E5%B8%A6%E4%BF%AE%E8%8E%AB%E9%98%9F%E3%80%81%E6%A0%91%E4%B8%8A%E8%8E%AB%E9%98%9F%E8%AF%A6%E8%A7%A3/ 

 这几天学习了莫队算法，试着写一篇比较详细的莫队教程吧… 普通莫队简介莫队是一种基于分块思想的离线算法，用于解决区间问题，适用范围如下：  只有询问没有修改。  允许离线。  在已知询问 $[l,r]$ 答案的情况下可以 $O(1)$  得到 $[l,r-1],[l,r+1],[l-1,r],[l+1,r]$ 的答案。   满足以上三个条件就可以在 $O(n\sqrt{m}+mlogm)$ 的时间复

**Comment by guoyangfan** [comment]
DD

**Comment by cjjzt** [comment]
感谢分享~
