### ISSUE TITLE
博客改用 utterances

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#84]
Gitalk [存在一些安全问题](https://www.v2ex.com/t/535608)，并且稳定性不好（最近就经常 Network Error），因此改用更加安全的 [utterances](https://github.com/utterance/utterances)。

[issues 存放仓库](https://github.com/ouuan/hexo-blog-utterances)

**Comment by ouuan** [comment]
fix #2

**Comment by code004Accepted** [comment]
您知道怎么设置吗qwq

**Comment by code004Accepted** [comment]
谷歌看到文章了，感谢dalao qwq

**Comment by ouuan** [comment]
> 本 hexo 博客几乎所有的美化、改造都能在 [hexo博客搭建指北](https://ouuan.github.io/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8C%97/) 中找到，如果有找不到的，可以在博客下方评论区留言。

[hexo博客搭建指北](https://ouuan.github.io/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8C%97/#评论功能)
