### ISSUE TITLE
utterances 加载不稳定

### ISSUE THREAD

**Issue by ouuan** [ouuan/ouuan.github.io#85]
加载用时从 1s 到 30s 不等。

**Comment by code004Accepted** [comment]
我刚刚才在想本地化的问题，但试过把那个js拷下来，好像用不了qwq

另：如果您的这个repo安装了utterances，是否我也可以通过代码来把我的博客的评论存储到您的issues里？貌似是一个Bug

**Comment by ouuan** [comment]
> 我刚刚才在想本地化的问题，但试过把那个js拷下来，好像用不了qwq
> 
> 另：如果您的这个repo安装了utterances，是否我也可以通过代码来把我的博客的评论存储到您的issues里？貌似是一个Bug

的确是可以存到别人的 issues 里..但评论本来就是谁都可以发的，感觉没啥问题。

**Comment by ouuan** [comment]
大约是可以诱导别人在错误的地方评论你的博客（

这种行为感觉无法避免

**Comment by ouuan** [comment]
因为现在加载时有 spinner 所以可以关了。
